// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TollGates;

namespace TollGates.Migrations
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20200827070639_wer")]
    partial class wer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TollGates.ScrewIdentifierGrid", b =>
                {
                    b.Property<int>("ScrewIdentifierGridId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiveOnMobileApp")
                        .HasColumnType("bit");

                    b.Property<bool>("ActiveOnWebApp")
                        .HasColumnType("bit");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<int>("Notifier")
                        .HasColumnType("int");

                    b.HasKey("ScrewIdentifierGridId");

                    b.ToTable("ScrewIdentifierGrid");
                });
#pragma warning restore 612, 618
        }
    }
}
